language: node_js
node_js:
  - '9'
  - '8'
  - '7'

notifications:
  email: false

before_install:
  - npm install -g istanbul babel-cli

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run build